/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.northeastern.charity.gui.Create;

/**
 *
 * @author sairammantravadi
 */
public class CreateUserPanel extends javax.swing.JPanel {

    /**
     * Creates new form UserPanel
     */
    public CreateUserPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UserInputPswrd = new javax.swing.JTextField();
        UserInputName = new javax.swing.JTextField();
        UserInputEmail = new javax.swing.JTextField();
        UserInputPhone = new javax.swing.JTextField();
        LblName = new javax.swing.JLabel();
        LblPswrd = new javax.swing.JLabel();
        LblEmail = new javax.swing.JLabel();
        LblPhone = new javax.swing.JLabel();
        BtnRegister = new javax.swing.JButton();
        LblTitle = new javax.swing.JLabel();

        setBackground(new java.awt.Color(36, 35, 39));

        UserInputPswrd.setBackground(new java.awt.Color(36, 35, 39));
        UserInputPswrd.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        UserInputPswrd.setForeground(new java.awt.Color(255, 255, 255));
        UserInputPswrd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        UserInputPswrd.setToolTipText("");
        UserInputPswrd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        UserInputPswrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserInputPswrdActionPerformed(evt);
            }
        });

        UserInputName.setBackground(new java.awt.Color(36, 35, 39));
        UserInputName.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        UserInputName.setForeground(new java.awt.Color(255, 255, 255));
        UserInputName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        UserInputName.setToolTipText("");
        UserInputName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        UserInputName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserInputNameActionPerformed(evt);
            }
        });

        UserInputEmail.setBackground(new java.awt.Color(36, 35, 39));
        UserInputEmail.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        UserInputEmail.setForeground(new java.awt.Color(255, 255, 255));
        UserInputEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        UserInputEmail.setToolTipText("");
        UserInputEmail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        UserInputEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserInputEmailActionPerformed(evt);
            }
        });

        UserInputPhone.setBackground(new java.awt.Color(36, 35, 39));
        UserInputPhone.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        UserInputPhone.setForeground(new java.awt.Color(255, 255, 255));
        UserInputPhone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        UserInputPhone.setToolTipText("");
        UserInputPhone.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        UserInputPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserInputPhoneActionPerformed(evt);
            }
        });

        LblName.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        LblName.setText("Name:");

        LblPswrd.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        LblPswrd.setText("Password:");

        LblEmail.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        LblEmail.setText("Email:");

        LblPhone.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        LblPhone.setText("Phone:");

        BtnRegister.setBackground(new java.awt.Color(0, 204, 255));
        BtnRegister.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N
        BtnRegister.setForeground(new java.awt.Color(255, 255, 255));
        BtnRegister.setText("Register");
        BtnRegister.setBorder(null);
        BtnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegisterActionPerformed(evt);
            }
        });

        LblTitle.setFont(new java.awt.Font("Open Sans", 1, 36)); // NOI18N
        LblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblTitle.setText("User Registration");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LblPswrd, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LblEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LblPhone, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UserInputName, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserInputPswrd, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserInputPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserInputEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(261, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(LblTitle)
                .addGap(241, 241, 241))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(285, 285, 285))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {UserInputEmail, UserInputName, UserInputPhone, UserInputPswrd});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(140, Short.MAX_VALUE)
                .addComponent(LblTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserInputName, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserInputEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserInputPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblPhone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserInputPswrd, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblPswrd))
                .addGap(18, 18, 18)
                .addComponent(BtnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(312, 312, 312))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void UserInputPswrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserInputPswrdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserInputPswrdActionPerformed

    private void UserInputNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserInputNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserInputNameActionPerformed

    private void UserInputEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserInputEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserInputEmailActionPerformed

    private void UserInputPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserInputPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserInputPhoneActionPerformed

    private void BtnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnRegisterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnRegister;
    private javax.swing.JLabel LblEmail;
    private javax.swing.JLabel LblName;
    private javax.swing.JLabel LblPhone;
    private javax.swing.JLabel LblPswrd;
    private javax.swing.JLabel LblTitle;
    private javax.swing.JTextField UserInputEmail;
    private javax.swing.JTextField UserInputName;
    private javax.swing.JTextField UserInputPhone;
    private javax.swing.JTextField UserInputPswrd;
    // End of variables declaration//GEN-END:variables
}
